Repository seoyoungsoo/goGetterProjectClient, pull requests merged in 2021-06, with the labels that each got.

#12 푸터 디자인 수정
  layouts/Footer/index.jsx
  layouts/Footer/styles.jsx
  pages/Modal/AuthModal.jsx
  pages/Modal/ServiceModal.jsx
  pages/SignUp/SignUp2/index.jsx
  pages/SignUp/SignUp2/styles.jsx
Labels: ♻️ Type : Refactoring, 🏷️Client

#16 토론게시판 구현중 pull 문제 해결
  README.md
  layouts/App/index.jsx
  layouts/Header/Navbar/LeftMenu/index.jsx
  pages/Discussion/index.jsx
  pages/Discussion/styles.jsx
Labels: 🏷️Client, 📄 Status : Reviewing

#23 토론게시판 상세게시판 View 작업
  layouts/App/index.jsx
  pages/Discussion/DCContent/index.jsx
  pages/Discussion/DCContent/styles.jsx
  pages/Discussion/index.jsx
  pages/Discussion/styles.jsx
Labels: 🏷️Client

#24 토론게시판 상세게시판 View 수정
  pages/Discussion/DCContent/index.jsx
  pages/Discussion/DCContent/styles.jsx
Labels: 🏷️Client

#25 헤더 View 수정
  layouts/Header/Navbar/index.jsx
  layouts/Header/Navbar/styles.jsx
Labels: 🏷️Client

#26 사이드바 View 수정, 헤더 View 수정
  components/Tab/styles.jsx
  layouts/Header/Navbar/styles.jsx
Labels: 🏷️Client

#27 [Modal & Style] 모달 및 스타일 수정
  components/Modal/Auth/index.jsx
  components/Modal/Service/index.jsx
  components/Modal/Service/styles.jsx
  components/Tab/styles.jsx
  pages/MyPage/Profile/index.jsx
  pages/MyPage/Profile/styles.jsx
  pages/SignUp/SignUp2/index.jsx
  pages/SignUp/SignUp2/styles.jsx
Labels: 🏷️Client, 👷 Type : Feature / Function

#30 게시글 작성 컴포넌트 구현 & 토론게시판 작성하기 페이지 구현
  components/WriteForm/index.jsx
  components/WriteForm/styles.jsx
  layouts/App/index.jsx
  pages/Discussion/DCWrite/index.jsx
  pages/Discussion/DCWrite/styles.jsx
  pages/Discussion/index.jsx
Labels: 🏷️Client, 🔨 Type : Component

#37 [BookRecord] 독서 기록 게시판 View 구현
  components/DiscussionWriteForm/index.jsx
  components/DiscussionWriteForm/styles.jsx
  components/RecordWriteForm/index.jsx
  components/RecordWriteForm/styles.jsx
  layouts/App/index.jsx
  layouts/Header/Navbar/index.jsx
  pages/Discussion/DCWrite/index.jsx
  pages/MyBookRecord/BRWrite/index.jsx
  pages/MyBookRecord/BRWrite/styles.jsx
  pages/MyBookRecord/index.jsx
  pages/MyBookRecord/styles.jsx
Labels: 🏷️Client

#39 [BRContent] 독서 기록 게시판 상세 페이지 구현
  components/DiscussionWriteForm/styles.jsx
  components/RecordWriteForm/styles.jsx
  layouts/App/index.jsx
  pages/MyBookRecord/BRContent/index.jsx
  pages/MyBookRecord/BRContent/styles.jsx
  pages/MyBookRecord/index.jsx
Labels: 🏷️Client, 👷 Type : Feature / Function

#40 [Header] 헤더 상단 고정
  layouts/Header/index.jsx
  layouts/Header/styles.jsx
  pages/MyBookRecord/BRContent/styles.jsx
Labels: 🏷️Client

#45 [Discussion] 토론 게시판 게시글 컴포넌트 구현
  pages/Discussion/index.jsx
  pages/Discussion/styles.jsx
Labels: 🏷️Client, 👷 Type : Feature / Function, 🔨 Type : Component

#46 [SignUp] 회원가입 구현
  pages/SignUp/SignUp2/index.jsx
Labels: 🏷️Client, 📄 Status : Reviewing

#52 [Redux & Refactoring] axios 재구성 / redux 구현 / 추가 수정
  actions/auth.js
  actions/message.js
  actions/type.js
  apis/authService.js
  client.jsx
  layouts/Header/Navbar/index.jsx
  package-lock.json
  package.json
  pages/LogIn/index.jsx
  pages/SignUp/SignUp2/index.jsx
  reducers/auth.js
  reducers/index.js
  reducers/message.js
  stores/index.js
  utils/authHeader.js
  webpack.config.js
Labels: ♻️ Type : Refactoring, 🏷️Client, 👷 Type : Feature / Function
