Repository seoyoungsoo/goGetterProjectClient, pull requests merged in 2021-07, with the labels that each got.

#59 [Auth & ShareBoard] 접근 권한 및 공유 게시판 view
  actions/auth.js
  actions/type.js
  apis/authService.js
  hoc/auth.js
  layouts/App/index.jsx
  layouts/Header/Navbar/index.jsx
  pages/LogIn/index.jsx
  pages/MyBookRecord/styles.jsx
  pages/ShareBoard/index.jsx
  pages/ShareBoard/styles.jsx
  pages/SignUp/SignUp2/index.jsx
  reducers/auth.js
  utils/authHeader.js
  utils/scrollToTop.js
  webpack.config.js
Labels: ♻️ Type : Refactoring, 🏷️Client, 👷 Type : Feature / Function, 📄 Status : InProgress, 🔨 Type : Component

#74 [SharedBoard] 공유 게시판
  components/Cards/index.jsx
  components/CardsPopular/index.jsx
  components/ShareBoardWriteForm/index.jsx
  components/ShareBoardWriteForm/styles.jsx
  hoc/auth.js
  pages/ShareBoard/ShareDetail/index.jsx
  pages/ShareBoard/Write/index.jsx
  pages/ShareBoard/index.jsx
  pages/ShareBoard/styles.jsx
Labels: 🏷️Client, 👷 Type : Feature / Function, 🔨 Type : Component

#76 [Reply & ShareBoard] 댓글 컴포넌트 분리 및 공유 게시판 적용
  components/RecordDetailContent/index.jsx
  components/RecordDetailContent/styles.jsx
  components/ShareBoardReply/index.jsx
  components/ShareBoardReply/styles.jsx
  components/ShareDetailContent/index.jsx
  components/ShareDetailContent/styles.jsx
  layouts/App/index.jsx
  pages/MyBookRecord/BRContent/index.jsx
  pages/MyBookRecord/BRContent/styles.jsx
  pages/ShareBoard/ShareDetail/index.jsx
  pages/ShareBoard/ShareDetail/styles.jsx
Labels: ♻️ Type : Refactoring, 🏷️Client, 👷 Type : Feature / Function, 🔨 Type : Component

#79 [Event] 이벤트 게시판 View/조회 구현
  components/Reply/index.jsx
  layouts/App/index.jsx
  layouts/Header/Navbar/index.jsx
  pages/Discussion/DCContent/index.jsx
  pages/Discussion/index.jsx
  pages/Discussion/styles.jsx
  pages/Event/Detail/index.jsx
  pages/Event/Detail/styles.jsx
  pages/Event/End/index.jsx
  pages/Event/End/styles.jsx
  pages/Event/Now/index.jsx
  pages/Event/Now/styles.jsx
Labels: 🏷️Client, 👷 Type : Feature / Function, 📄 Status : InProgress

#85 [EventWrite] 이벤트 작성하기 기능 구현중
  components/EventWriteForm/index.jsx
  components/EventWriteForm/styles.jsx
  layouts/App/index.jsx
  pages/Discussion/index.jsx
  pages/Event/Detail/index.jsx
  pages/Event/Detail/styles.jsx
  pages/Event/Write/index.jsx
  pages/Event/Write/styles.jsx
Labels: 🏷️Client, 📄 Status : InProgress, 🔨 Type : Component

#104 이벤트 작성 쿠폰 추가, 수정/삭제 모달 구현
  components/EventWriteForm/index.jsx
  components/EventWriteForm/styles.jsx
  components/Modal/EventDelete/index.jsx
  components/Modal/EventDelete/styles.jsx
  components/Modal/EventEdit/index.jsx
  components/Modal/EventEdit/styles.jsx
  pages/Event/Detail/index.jsx
  pages/Event/Detail/styles.jsx
  pages/Event/Now/index.jsx
  pages/Event/Now/styles.jsx
  pages/Event/Write/index.jsx
Labels: 🏷️Client, 👷 Type : Feature / Function, 🔨 Type : Component

#107 [Admin] 관리자 페이지 구현
  components/AdminTab/index.jsx
  components/AdminTab/styles.jsx
  components/Modal/MemberDelete/index.jsx
  components/Modal/MemberDelete/styles.jsx
  components/Paging/index.jsx
  layouts/App/index.jsx
  layouts/Header/Navbar/index.jsx
  pages/Admin/index.jsx
  pages/Admin/styles.jsx
  pages/Discussion/index.jsx
  utils/formatPhoneNumber.js
Labels: 🏷️Client, 👷 Type : Feature / Function

#110 [Admin] 관리자 페이지 월별 회원가입수 그래프 구현
  components/AdminTab/index.jsx
  components/AdminTab/styles.jsx
  layouts/App/index.jsx
  package-lock.json
  package.json
  pages/Admin/Monthly/index.jsx
  pages/Admin/Monthly/styles.jsx
  pages/Admin/index.jsx
  pages/Event/Detail/index.jsx
  pages/Event/Now/index.jsx
Labels: 🏷️Client, 👷 Type : Feature / Function
